language: node_js
node_js:
  - "11"
branches:
  only:
  - source #源码分支名称
before_install:
- npm install -g hexo 
- npm install -g hexo-cli
before_script:
- git config user.name "janeldq"
- git config user.email "janeldq@163.com"
- sed -i'' "s~https://github.com/JaneLdq/janeldq.github.io.git~https://${GITHUB_ACCESS_TOKEN}@github.com/JaneLdq/janeldq.github.io.git~" _config.yml
install:
- npm install --no-optional
script:
- git clone --depth 1 --branch=master https://github.com/JaneLdq/janeldq.github.io.git .deploy_git

- cd .deploy_git

# Remove all files before they get copied from ../public/
# so git can track files that were removed in the last commit
- find . -path ./.git -prune -o -exec rm -rf {} \; 2> /dev/null

- cd ../

# Run deployment
- hexo clean
- hexo generate
- hexo deploy
